### ISSUE TITLE
Create a gh-pages branch for QA before pushing to the production server

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#32]
We should be able to browse and QA the content of /WebSite/ on http://shenkarlab.github.io/Off-The-record/WebSite/

**Comment by nir-jackson** [comment]
it will have the same problem as running it from my machine, the data won't be under the same domain and it won't work.
@mushon

**Comment by mushon** [comment]
@nir-jackson I doubt that. Reading JSON remotely is trivial. Your problem is probably in making sure links are relative when they need to be relative and absolute when they need to be absolute.

Anyway, the code is updated on the Calcalist site (http://viz.calcalist.co.il/otr/web/) please have the whole group @shenkarlab/off-the-record review it, document the last bugs (especially in the case of missing posts, @akariv thinks it might be due to missing posts from Kikar Hamedina) and let's launch this thing. @Amitasulin9 @eldadtzadok @moranbz, please confirm you're seeing this, I want to see you documenting bugs and responding to issues.

**Comment by nir-jackson** [comment]
@mushon i know its because of missing posts from kikar hamedina. I've mentioned this problem several times.... kikar only has posts from (around) 2012. 

i don't see the point of uploading the site to http://shenkarlab.github.io/Off-The-record/WebSite/.

did you also rerun the python scripts? did you delete the old data before as i asked?

**Comment by akariv** [comment]
yes

**Comment by mushon** [comment]
Since this issue isn't done, I'm reopening this ticket and marking it to the "After Launch" milestone.
